plugins {
	id "net.fabricmc.fabric-loom" version "${loom_version}"
	id "com.diffplug.spotless" version "${spotless_version}"
}

def mod_props = [
	"mod_group_id": property("mod.group_id"),
	"mod_id": property("mod.id"),
	"mod_version": property("mod.version"),
	"mod_name": property("mod.name"),
	"mod_description": property("mod.description"),
	"mod_author": property("mod.author"),
	"mod_license": property("mod.license"),
]

def dep_versions = [
	"minecraft_version": sc.current.version,
	"loader_version": property("deps.loader"),
	"fabric_api_version": property("deps.fabric_api"),
	"polymer_version": property("deps.polymer")
]

version = "${mod_props["mod_version"]}+${dep_versions["minecraft_version"]}"
base.archivesName = mod_props["mod_id"]
def java_version = JavaVersion.VERSION_25
def java_version_int = java_version.majorVersion.toInteger()

repositories {
	maven { url "https://maven.nucleoid.xyz" }
}

dependencies {
	minecraft "com.mojang:minecraft:${dep_versions["minecraft_version"]}"
	implementation "net.fabricmc:fabric-loader:${dep_versions["loader_version"]}"
	implementation "net.fabricmc.fabric-api:fabric-api:${dep_versions["fabric_api_version"]}"
	compileOnly "eu.pb4:polymer-core:${dep_versions["polymer_version"]}"
	compileOnly "eu.pb4:polymer-resource-pack:${dep_versions["polymer_version"]}"
}

processResources {
	filesMatching("fabric.mod.json") {
		expand(mod_props + dep_versions)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version_int
}

java {
	withSourcesJar()
	sourceCompatibility = java_version
	targetCompatibility = java_version
}

jar {
	from("LICENSE") {
		rename { "${it}_${mod_props["mod_group_id"]}"}
	}
}

spotless {
	java {
		importOrder()
		removeUnusedImports()
		shortenFullyQualifiedTypes()

		// princeOfSpace("2.2.0")
		// 	.indentStyle("TABS")
		// 	.indentSize(1)
		// 	.trailingCommas(true)
		// 	.javaLanguageLevel(java_version_int)

		formatAnnotations()
	}
}
