plugins {
	id "net.fabricmc.fabric-loom" version "${loom_version}"
	id "dev.kikugie.fletching-table.fabric" version "${fletching_table_version}"
	id "dev.kikugie.fletching-table.mixin" version "${fletching_table_version}"
}

def java_version = JavaVersion.VERSION_25
def java_version_int = java_version.majorVersion.toInteger()

def mod_props = [
	"mod_group_id": property("mod.group_id"),
	"mod_id": property("mod.id"),
	"mod_version": property("mod.version"),
	"mod_name": property("mod.name"),
	"mod_description": property("mod.description"),
	"mod_author": property("mod.author"),
	"mod_license": property("mod.license"),
]

def dep_versions = [
	"minecraft_version": sc.current.version,
	"loader_version": property("deps.loader"),
	"fabric_api_version": property("deps.fabric_api"),
	"polymer_version": property("deps.polymer"),
	"java_version": java_version_int,
]

version = "${mod_props["mod_version"]}+${dep_versions["minecraft_version"]}"
base.archivesName = mod_props["mod_id"]

repositories {
	maven { url "https://maven.nucleoid.xyz" }
}

dependencies {
	minecraft "com.mojang:minecraft:${dep_versions["minecraft_version"]}"
	implementation "net.fabricmc:fabric-loader:${dep_versions["loader_version"]}"
	implementation "net.fabricmc.fabric-api:fabric-api:${dep_versions["fabric_api_version"]}"
	compileOnly "eu.pb4:polymer-core:${dep_versions["polymer_version"]}"
	compileOnly "eu.pb4:polymer-resource-pack:${dep_versions["polymer_version"]}"
}

processResources {
	filesMatching([
		"fabric.mod.json",
		"*.mixins.json"
	]) {
		expand(mod_props + dep_versions)
	}
}

fletchingTable {
	fabric.configure(sourceSets.main) {}

	mixins.configure(sourceSets.main) {
		mixin("${mod_props["mod_id"]}.mixins.json")
	}
}

loom {
	runConfigs.all {
		preferGradleTask = true
		generateRunConfig = true
		runDirectory = rootProject.file("run")
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = java_version_int
}

java {
	withSourcesJar()
	sourceCompatibility = java_version
	targetCompatibility = java_version
}

jar {
	from("license.md") {
		rename { "${it}_${mod_props["mod_group_id"]}"}
	}
}

def jar_name = "${mod_props["mod_id"]}-${version}"

tasks.register("buildAndCollect") {
	group = "build"
	dependsOn(tasks.named("build"))

	doLast {
		for (file in [
			"${jar_name}",
			"${jar_name}-sources"
		]) {
			copy {
				from layout.buildDirectory.file("libs/${file}.jar")
				into rootProject.layout.buildDirectory.file("libs")
			}
		}
	}
}
