# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
dev.kikugie.stonecutter.hard_mode=true

gitignore_to_glob_cli_version=0.1.1
node_gradle_version=7.1.0
prettier_version=3.9.9
prettier_java_version=2.10.4
prettier_toml_version=3.0.2
prettier_properties_version=0.3.1
spotless_version=8.10.2

fletching_table_version=0.2.0-alpha.9
loom_version=1.18-SNAPSHOT
stonecutter_version=0.9.8
