plugins {
	id "dev.kikugie.stonecutter"
	id "com.diffplug.spotless" version "${spotless_version}"
	id "com.github.node-gradle.node" version "${node_gradle_version}"
}

repositories {
	mavenCentral()
}

stonecutter.active "26.3"

def gitignoreFile = rootProject.file(".gitignore")
def gitignoreOutput = layout.buildDirectory.file("gitignore.txt")

task gitignore(type: NpxTask) {
	// command = "gitignore-to-minimatch-cli"
	command = "tommy-mitchell/gitignore-to-minimatch-cli"
	args = ["-i", gitignoreFile.absolutePath]

	inputs.file(gitignoreFile)
	outputs.file(gitignoreOutput)

	execOverrides {
		standardOutput = new FileOutputStream(gitignoreOutput.get().asFile)
	}
}

def excludePatterns = providers.provider {
	def patterns = gitignoreOutput.get().asFile.readLines()
	rootProject.fileTree(rootProject.projectDir) {
		include(patterns)
	}
}

def prettier_version = [prettier: prettier_version]
def prettier_plugins = [
	"prettier-plugin-toml": prettier_toml_version,
	"prettier-plugin-properties": prettier_properties_version,
]
def prettier_options = [
	useTabs: true,
	printWidth: 120,
]

spotless {
	enforceCheck = false

	java {
		target "src/*/java/**/*.java"

		toggleOffOn()
		shortenFullyQualifiedTypes()
		importOrder()
		removeUnusedImports()

		cleanthat()

		// formatter
		prettier(prettier_version + ["prettier-plugin-java": prettier_java_version])
		.config([parser: "java", plugins: ["prettier-plugin-java"]] + prettier_options + [
			arrowParens: "avoid",
			experimentalOperatorPosition: "start",
		])
	}
	// groovyGradle {
	// 	greclipse().configProperties("""
	// 		ignoreFormatterProblems=true
	// 		groovy.formatter.remove.unnecessary.semicolons=true
	// 		groovy.formatter.string.literal.quote.style=2
	// 	""")
	// }
	// format "gradle", {
	// 	target "**/*.gradle"
	// 	prettier(prettier_version + ["prettier-plugin-groovy": prettier_groovy_version])
	// 	.config([parser: "groovy", plugins: "prettier-plugin-groovy"] + prettier_options)
	// }
	format "prettier", {
		target "**/*.json", "**/*.yaml", "**/*.yml", "**/*.toml", "**/*.properties", "**/*.md"
		targetExclude excludePatterns // see diffplug/spotless#2443

		prettier(prettier_version + prettier_plugins)
		.config([plugins: prettier_plugins.keySet().toArray()] + prettier_options + [
			keySeparator: "="
		])
	}
}

tasks.named("spotlessPrettier").configure {
    dependsOn gitignore
}
